name: Unit Test
on:
  push

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Go to the commit that triggered workflow
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
          cache: gradle
      - name: Run unit tests
        run: |
          cd altaicheckers
          chmod +x gradlew
          ./gradlew test

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
